'use client';
import React, { useState } from 'react';




const FaqItem = ({ question, answer }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (
      <div className="mb-4">
        <button
          className="flex justify-between items-center w-full px-4 py-2 text-left text-gray-800 bg-gray-100 hover:bg-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
          onClick={() => setIsOpen(!isOpen)}
        >
          <span className="font-medium">{question}</span>
          <span>{isOpen ? '-' : '+'}</span>
        </button>
        {isOpen && <div className="mt-2 p-4 bg-white rounded-lg shadow">{answer}</div>}
      </div>
    );
  };
  
  
 const   FaqList = () => {
    const faqs = [
      {
        question: 'What is Real AI?',
        answer: 'Real AI is an innovative application that uses artificial intelligence to generate unique images from textual descriptions. Simply enter a description of the image you have in mind, and the app will create a visual representation for you.'
      },
      {
        question: 'How does Real AI work?',
        answer: 'Real AI utilizes advanced AI models, such as DALL-E or similar technologies, to interpret your text prompts and translate them into images. The AI has been trained on a diverse dataset of images and text, allowing it to understand a wide range of concepts and styles.'
      },
      {
        question: 'Can I create any type of image with Real AI?',
        answer: 'While Real AI is quite versatile and can generate a variety of images, there are limitations. The AI may not perform well with extremely detailed or complex prompts, and it is programmed to avoid creating images that contain explicit content or violate copyright laws.'
      },
      {
        question: 'Is the content generated by Real AI copyrighted?',
        answer: 'The images generated by Real AI are typically free to use for personal or commercial purposes, but it is important to review the terms of service for specific usage rights and restrictions. Always ensure that the generated images do not infringe on existing copyrights or trademarks.'
      },
    
      
      // ... other FAQs
    ];
    return (
      <div className="">
       <div className="flex flex-col items-center bg-primary-200 text-white w-full py-5">
            <h1 className="text-2xl">Frequent Questions</h1>
            <hr className="w-1/2 border-pink-500 mt-2" />
        </div>
        <div className="">
        
                  <div className="p-4">
            {faqs.map((faq, index) => (
              <FaqItem key={index} question={faq.question} answer={faq.answer} />
            ))}
                  </div>
        
                  <footer class="bg-gray-800 text-white p-4">
         <div class="max-w-screen-xl mx-auto">
            <div class="grid grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-1 gap-4">
        <div class="text-center">
          <p class="text-sm">
            Copyright &copy; 2024 
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-yellow-400 via-yellow-500 to-yellow-600 hover:underline"> REAL AI </span> 
            
            Co., Ltd. All Rights Reserved.
        
            Design: <a href="#" target="_blank" rel="noopener noreferrer" class="text-blue-500 underline">Tunis</a>
          </p>
        </div>
            </div>
         </div>
        </footer>
        </div>
      </div>
    );
  };

  export default FaqList